### ISSUE TITLE
SocketException: Unrecognized Windows Sockets error: 11: connect

### ISSUE THREAD

**Issue by superstrom** [ikvm-revived/ikvm-maven#22] opened 2022-11-20 14:32 UTC
I created a simple project with a MavenReference and a simple GitHub action to build it. (https://github.com/superstrom/PB)
When the action is run by ubuntu-latest, I get a "SocketException: Unrecognized Windows Sockets error: 11: connect" error.

/home/runner/.nuget/packages/ikvm.maven.sdk/1.1.0/buildTransitive/netstandard2.0/IKVM.Maven.Sdk.targets(96,9): error : ArtifactTransferException: Could not transfer artifact org.apache.pdfbox:pdfbox:pom:2.0.27 from/to central (https://repo1.maven.org/maven2/): Unrecognized Windows Sockets error: [11](https://github.com/superstrom/PB/actions/runs/3508367455/jobs/5876724869#step:5:12): connect [/home/runner/work/PB/PB/PB/PB.csproj]
/home/runner/.nuget/packages/ikvm.maven.sdk/1.1.0/buildTransitive/netstandard2.0/IKVM.Maven.Sdk.targets(96,9): error :  [/home/runner/work/PB/PB/PB/PB.csproj]
/home/runner/.nuget/packages/ikvm.maven.sdk/1.1.0/buildTransitive/netstandard2.0/IKVM.Maven.Sdk.targets(96,9): error : SocketException: Unrecognized Windows Sockets error: 11: connect [/home/runner/work/PB/PB/PB/PB.csproj]
/home/runner/.nuget/packages/ikvm.maven.sdk/1.1.0/buildTransitive/netstandard2.0/IKVM.Maven.Sdk.targets(96,9): error :    at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpUriRequest , EntityGetter ) [/home/runner/work/PB/PB/PB/PB.csproj]
/home/runner/.nuget/packages/ikvm.maven.sdk/1.1.0/buildTransitive/netstandard2.0/IKVM.Maven.Sdk.targets(96,9): error :    at org.eclipse.aether.transport.http.HttpTransporter.implGet(GetTask ) [/home/runner/work/PB/PB/PB/PB.csproj]
/home/runner/.nuget/packages/ikvm.maven.sdk/1.1.0/buildTransitive/netstandard2.0/IKVM.Maven.Sdk.targets(96,9): error :    at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(GetTask task) [/home/runner/work/PB/PB/PB/PB.csproj]
/home/runner/.nuget/packages/ikvm.maven.sdk/1.1.0/buildTransitive/netstandard2.0/IKVM.Maven.Sdk.targets(96,9): error :    at org.eclipse.aether.connector.basic.BasicRepositoryConnector.GetTaskRunner.runTask() [/home/runner/work/PB/PB/PB/PB.csproj]
/home/runner/.nuget/packages/ikvm.maven.sdk/1.1.0/buildTransitive/netstandard2.0/IKVM.Maven.Sdk.targets(96,9): error :    at org.eclipse.aether.connector.basic.BasicRepositoryConnector.TaskRunner.run() [/home/runner/work/PB/PB/PB/PB.csproj]
/home/runner/.nuget/packages/ikvm.maven.sdk/1.1.0/buildTransitive/netstandard2.0/IKVM.Maven.Sdk.targets(96,9): error :  [/home/runner/work/PB/PB/PB/PB.csproj]

I don't know if this is a GitHub Actions issue, or an IKVM issue.

**Comment by wasabii** [comment] 2022-11-20 14:35
https://github.com/ikvm-revived/ikvm/pull/103

**Comment by wasabii** [comment] 2022-11-20 14:35
It is however a duplicate of #9

**Closed by wasabii** 2022-11-20 14:35 UTC
